#
# Installation
#
- name: Add apt key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: Add apt repository
  apt_repository: repo='deb http://mirror.netinch.com/pub/mariadb/repo/10.1/ubuntu trusty main' state=present

- name: Install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: mariadb_packages

#
# Configuration
#
- name: Get list of hosts for the root user
  command: mysql -u root -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mariadb_root_hosts
  changed_when: false

- name: Get list of hosts for the anonymous user
  command: mysql -u root -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mariadb_anonymous_hosts
  changed_when: false

- name: Remove anonymous users
  mysql_user:
   name: ""
   host: "{{ item }}"
   state: absent
  with_items: mariadb_anonymous_hosts.stdout_lines

- name: Remove test database
  mysql_db: "name='test' state=absent"

- name: Update database root password
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mariadb_root_password }}"
  with_items: mariadb_root_hosts.stdout_lines

- name: Copy .my.cnf file with root password credentials
  template:
    src: "user-my.cnf.j2"
    dest: "{{ mariadb_user_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600

