---
- name: Ensure MySQL Python libraries are installed.
  yum: "name=MySQL-python state=installed enablerepo={{ mysql_enablerepo }}"

- name: Ensure MySQL packages are installed.
  yum: "name={{ item }} state=installed enablerepo={{ mysql_enablerepo }}"
  with_items: mysql_packages
