- name: Install packages
  apt: pkg=newrelic-php5
       state=latest
       update_cache=yes

- name: Configure using template
  template: dest="/etc/php5/mods-available/newrelic.ini"
            src="newrelic.ini.j2"
  notify: restart php5-fpm
