# Main playbook that applies to all hosts
- hosts: all
  connection: local
  sudo: true
  vars:
    hostname: nginx-php-mariadb-nodejs
    nginx_host_template: default-php.j2
  roles:
    - init
    - nginx
    - php5
    - mariadb

# Vagrant-specific playbook
- hosts: vagrant
  connection: local
  sudo: true
  roles:
    - xdebug
    - nodejs
