# Main playbook that applies to all hosts
- hosts: all
  connection: local
  sudo: true
  vars:
    hostname: nginx-php-mariadb-nodejs
  vars_files:
    - vars/nginx.yml
    - vars/php.yml
    - vars/mariadb.yml
  roles:
    - init
    - nginx
    - php5
    - mariadb
    - nodejs

# Vagrant-specific playbook
- hosts: vagrant
  connection: local
  sudo: true
  vars_files:
    - vars/xdebug.yml
  roles:
    - xdebug
