php_ppa: php5-5.6
php_packages:
  - php5-cli
  - php5-fpm
  - php5-curl
  - php5-gd
  - php5-imagick
  - php5-intl
  - php5-mcrypt
  - php5-mysql
  - phpunit
php_fpm_pool_www_file: /etc/php5/fpm/pool.d/www.conf
php_fpm_pool_www_template: fpm_pool_www.j2

php_fpm_ini_file: /etc/php5/fpm/php.ini
php_fpm_ini_template: php.ini.j2

# make sure you use matching values for nginx too
php_upload_max_filesize: 10M
php_post_max_size: 10M

php_timezone: Europe/Helsinki
