- name: Add apt repository
  apt_repository: repo=ppa:ondrej/{{ php_ppa }}

- name: Install packages
  apt: pkg=php5-xdebug state=latest update_cache=yes

- name: Configure xdebug
  template:
    src: xdebug.ini.j2
    dest: "{{ php_extension_path }}/xdebug.ini"
    owner: root
    group: root
    mode: 0644
