- name: Add apt repository
  apt_repository: repo="ppa:brightbox/ruby-ng"
                  update_cache=yes

- name: Install packages
  apt: pkg={{ item }}
  with_items: "{{ ruby_packages }}"

- name: Install gems
  command: gem install {{ item }}
  with_items: "{{ ruby_gems }}"
