- name: Update apt
  apt: update_cache=yes

- name: Install Additional Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - htop
    - screen
    - tmux
    - git
    - vim
    - curl
    - git-core
    - python-software-properties
    - wget
    - zsh

- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
