- name: Add apt repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php_ppa }}

- name: Install SAPIs
  apt: pkg={{ item.package }} state=latest update_cache=yes
  with_items: php_sapis

- name: Install modules
  sudo: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: php_packages

- name: Check if php5-fpm is installed
  stat: path=/usr/sbin/php5-fpm
  register: php_fpm_exists

- name: Configure php5-fpm to use TCP/IP rather than a socket
  sudo: yes
  template: src={{ php_fpm_pool_www_template }} dest={{ php_fpm_pool_www_file }}
  notify: restart php5-fpm
  when: php_fpm_exists.stat.exists == True

- name: Configure all installed SAPIs with php.ini using template
  sudo: yes
  template: src={{ php_fpm_ini_template }} dest=/etc/php5/{{ item.name }}/php.ini
  with_items: php_sapis
  notify: restart php5-fpm

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
