- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php_ppa }}

- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-fpm

- name: Install extensions
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: Configure php5-fpm to use TCP/IP rather than a socket
  sudo: yes
  template: src={{ php_fpm_pool_www_template }} dest={{ php_fpm_pool_www_file }}
  notify: restart php5-fpm

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
