- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest update_cache=yes

- name: Change default nginx site
  sudo: yes
  template: src={{ nginx.host_template }} dest={{ nginx.host_file }}
  notify: restart nginx
