- name: Install packages
  sudo: yes
  apt: pkg=nginx state=latest update_cache=yes cache_valid_time=3600

- name: Check if web root exists
  stat: path={{ nginx_web_root }}
  register: web_root_stat

- name: Create web root directory
  file: path={{ nginx_web_root }} state=directory
  when: not web_root_stat.stat.exists

- name: Ensure web root directory has proper permissions
  file: path={{ nginx_web_root }}
        owner={{ nginx_web_user }}
        group={{ nginx_web_group }}
        mode="u=rwX,g=rwXs,o=rX"
  when: not web_root_stat.stat.exists

- name: Change default nginx site
  sudo: yes
  template: src={{ nginx_host_template }} dest={{ nginx_host_file }}
  notify: restart nginx

#
# Configuration for additional sites (not always used)
#
- name: Add potential additional sites
  template: src={{ item.host_template }} dest={{ item.host_file }}
  with_items: nginx_additional_sites | default([])
  notify: restart nginx

- name: Ensure additional web roots exist
  file: path={{ item.web_root }} state=directory
  with_items: nginx_additional_sites | default([])

- name: Ensure additional web root directories have proper permissions
  file: path={{ item.web_root }}
        owner={{ nginx_web_user }}
        group={{ nginx_web_group }}
        mode="u=rwX,g=rwXs,o=rX"
  with_items: nginx_additional_sites | default([])

- name: Ensure all available sites are enabled
  file: src=/etc/nginx/sites-available/{{ item | basename }} dest=/etc/nginx/sites-enabled/{{ item | basename }} state=link
  with_fileglob: /etc/nginx/sites-available/*
  notify: restart nginx

- name: Ensure services are started
  service: name=nginx state=started
