#
# The domain name (or names) the server should serve requests for
#
nginx_server_name: "{{ hostname }}"

#
# Domain names that should be redirected to the domain specified by nginx_server_aliases_redirect
#
nginx_server_aliases: ""

#
# The domain to redirect all nginx_server_aliases to
#
nginx_server_aliases_redirect: ""
nginx_web_root: /var/www
nginx_web_user: www-data
nginx_web_group: www-data
nginx_host_file: /etc/nginx/sites-available/default

#
# This role comes with two basic templates, one without PHP support and one with
#
nginx_host_template: default.j2

#
# Whether sendfile should be enabled or not
#
nginx_sendfile: off

#
# Only applicable when PHP is used
#
nginx_fastcgi_pass: localhost:9000

#
# Maximum upload size that can be sent by a client
#
nginx_client_max_body_size: 10m

#
# Additional sites to configure. Each item should be a dictionary with the following keys:
# web_root, host_template, host_file
#
nginx_additional_sites: []
