- name: Download the archive
  command: curl -o {{ packer_archive_path }} https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip

- name: Unpack the archive
  unarchive: src={{ packer_archive_path }} dest=/usr/local/bin copy=no

- name: Delete the archive
  file: path={{ packer_archive_path }} state=absent
