- name: "Ensure backup target directory exists"
  file: path={{ mariadb_backup_path }}
        state=directory
        owner={{ mariadb_backup_username }}
        group={{ mariadb_backup_username }}
        mode=0755

- name: "Create daily database backup job"
  cron: name="daily database backup"
        user={{ mariadb_backup_username }}
        minute="0"
        hour="6"
        job="mysqldump -h {{ mariadb_backup_database_hostname }} {{ mariadb_backup_mysqldump_options }} {{ item }} | gzip > {{ mariadb_backup_path }}/{{ item }}_daily_`date +\%Y-\%m-\%d_\%H\%M\%S`.sql.gz"
  with_items: "{{ mariadb_backup_databases }}"

- name: "Create weekly database backup job"
  cron: name="weekly database backup"
        user={{ mariadb_backup_username }}
        minute="30"
        hour="6"
        weekday="0"
        job="mysqldump -h {{ mariadb_backup_database_hostname }} {{ mariadb_backup_mysqldump_options }} {{ item }} | gzip > {{ mariadb_backup_path }}/{{ item }}_weekly_`date +\%Y-\%m-\%d_\%H\%M\%S`.sql.gz"
  with_items: "{{ mariadb_backup_databases }}"

- name: "Create remove obsolete daily backups jobs"
  cron: name="remove obsolete daily backups"
        user={{ mariadb_backup_username }}
        special_time="daily"
        job="find {{ mariadb_backup_path }} -name '*daily*' -mtime +{{ mariadb_backup_daily_to_keep - 1 }} -exec rm {} \;"

- name: "Create remove obsolete weekly backups jobs"
  cron: name="remove obsolete weekly backups"
        user={{ mariadb_backup_username }}
        special_time="weekly"
        job="find {{ mariadb_backup_path }} -name '*weekly*' -mtime +{{ mariadb_backup_weekly_to_keep * 7 - 1 }} -exec rm {} \;"

- name: "Create synchronize with S3 job"
  cron: name="synchronize with S3"
        user={{ mariadb_backup_username }}
        minute="0"
        hour="9"
        job="/usr/local/bin/aws s3 sync {{ mariadb_backup_path }} s3://{{ mariadb_backup_s3_bucket }}/{{ mariadb_backup_s3_directory }} --region {{ mariadb_backup_s3_region }}"

- name: Copy .my.cnf file with root password credentials
  template: src="user-my.cnf.j2"
            dest="/home/{{ mariadb_backup_username }}/.my.cnf"
            owner={{ mariadb_backup_username }}
            group={{ mariadb_backup_username }}
            mode=0600
