- name: Install packages
  apt: pkg=sphinxsearch update_cache=yes cache_valid_time=3600

- name: Configure /etc/sphinxsearch/sphinx.conf
  copy: src={{ sphinx_config_file }} dest=/etc/sphinxsearch/sphinx.conf

- name: Configure /etc/default/sphinxsearch using template
  template: src=sphinx.default.conf.j2 dest=/etc/default/sphinxsearch

- name: Ensure service is disabled and stopped (cannot start without index)
  service: name=sphinxsearch state=stopped enabled=false
