- name: Add apt repository
  shell: curl -sL https://deb.nodesource.com/setup_{{ nodejs_version }} | sudo -E bash -

- name: Install packages
  apt: pkg=nodejs state=latest update_cache=yes

- name: Install global npm packages
  shell: "which {{item}} || npm install -g {{item}}"
  with_items: "{{ nodejs_npm_global_packages }}"
