- name: Download the archive
  command: curl -o {{ terraform_archive_path }} https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip

- name: Unpack the archive
  unarchive: src={{ terraform_archive_path }} dest=/usr/local/bin copy=no

- name: Delete the archive
  file: path={{ terraform_archive_path }} state=absent
