- name: Add apt key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg
           state=present

- name: Add apt repository
  template: dest="/etc/apt/sources.list.d/newrelic-servers.list"
            src="newrelic-servers.list.j2"

- name: Install packages
  apt: pkg=newrelic-sysmond
       state=latest
       update_cache=yes

- name: Configure license
  command: nrsysmond-config --set license_key={{ newrelic_servers_license_key }}

- name: Ensure service is enabled and running
  service: name=newrelic-sysmond state=started enabled=true
