- name: Install the Letsencrypt client
  git: repo=https://github.com/letsencrypt/letsencrypt
       dest={{ letsencrypt_path }}

- name: Register certificate request/renewal command
  set_fact:
    letsencrypt_command: "{{ letsencrypt_path }}/letsencrypt-auto certonly --webroot --agree-tos --expand --email {{ letsencrypt_email }} {{ letsencrypt_webroot_domain_parameters }} "
    letsencrypt_cronjob_command: "{{ letsencrypt_path }}/letsencrypt-auto certonly --webroot --agree-tos --expand --force-renewal --email {{ letsencrypt_email }} {{ letsencrypt_webroot_domain_parameters }} "

- name: Request certificates
  command: "{{ letsencrypt_command }}"

- name: Add renewal cronjob
  cron: name="Renew Letsencrypt certificates"
        user="{{ letsencrypt_cronjob_user }}"
        special_time="monthly"
        job="{{ letsencrypt_cronjob_command }}"
