- name: Add apt key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch
           state=present

- name: Add apt repository
  template: dest="/etc/apt/sources.list.d/elasticsearch.list"
            src="elasticsearch.list.j2"

- name: Install packages
  apt: pkg=elasticsearch
       state=latest
       update_cache=yes

- name: Ensure service is enabled and running
  service: name=elasticsearch state=started enabled=true

- name: Configure using template
  template: dest="/etc/elasticsearch/elasticsearch.yml"
            src="elasticsearch.yml.j2"
  notify: restart elasticsearch
